const SHOW_HTTP_ERROR = 'SHOW_HTTP_ERROR'
const NOT_SHOW_HTTP_ERROR = 'NOT_SHOW_HTTP_ERROR'
const SET_CARD_WIDTH = 'SET_CARD_WIDTH'
const SET_VW = 'SET_VW'
const SET_CARD_TO_CLIENT_LEFT = 'SET_CARD_TO_CLIENT_LEFT'

export default {
  SHOW_HTTP_ERROR,
  NOT_SHOW_HTTP_ERROR,
  SET_CARD_WIDTH,
  SET_VW,
  SET_CARD_TO_CLIENT_LEFT
}
